---
title: "Data Cleaning"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
```
Loading the exposure data
```{r}
neighbor_data = 
  read_excel("./Data/temp_data.xlsx", sheet = 2) %>%
  janitor::clean_names() %>% 
  select(-c(x1)) %>% 
    mutate(ceb = as.numeric(ceb),
           median_age = as.numeric(median_age),
           percent_female = as.numeric(percent_female),
           fuel_used_for_cooking_percent_wood_dung = as.numeric(fuel_used_for_cooking_percent_wood_dung),
           percent_public_source = as.numeric(percent_public_source),
           percent_private_toilet = as.numeric(percent_private_toilet),
           percent_employed = as.numeric(percent_employed),
           percent_without_hs_education = as.numeric(percent_without_hs_education),
           percent_marital_status = as.numeric(percent_marital_status),
           percent_caste = as.numeric(percent_caste)
         ) 

head(neighbor_data)
```


Loading and cleaning the outcome data
```{r message=FALSE, warning=FALSE}
outcome_data = 
  read_excel("./Data/temp_data.xlsx", sheet = 3) %>%
  separate(sbp, into = c("sbp", "sbp_sd")) %>% 
  separate(dbp, into = c("dbp", "dbp_sd")) %>% 
  separate(  bmi, into = c("bmi", "bmi_sd")) %>% 
  janitor::clean_names() %>% 
  mutate(ceb = as.numeric(ceb),
         fbg = as.numeric(fbg),
         fbg_sd = as.numeric(fbg_sd),
         sbp = as.numeric(sbp),
         sbp_sd = as.numeric(sbp_sd),
         dbp = as.numeric(dbp),
         dbp_sd = as.numeric(dbp_sd),
         bmi = as.numeric(bmi),
         bmi_sd = as.numeric(bmi_sd),
         hypertension = as.numeric(hypertension),
         diabetes = as.numeric(diabetes)
         ) %>% 
  select(ceb, fbg, sbp, dbp, bmi)
outcome_data
```

Categorizing BMI, FBG
```{r}
outcome_two_data=
  outcome_data %>% 
  mutate(bmi_cat = ifelse(bmi >=25, "obese", 
                          ifelse(bmi>=23 & bmi<=24.9, "overweight",
                          "normal")),
         fbg_cat = ifelse(fbg >=126, "diabetes", 
                          ifelse(fbg>=110 & fbg<=125.9, "prediabetes",
                          "normal")),
         hyp_cat = ifelse(sbp <120 | dbp<80, "normal", 
                          ifelse(sbp>=120 & fbg<=155.9 | dbp>=90 & fbg<=99.9, "hypertensive",
                          "hypertension"))
         )
outcome_two_data
```

Merge outcome_two_data and neighbor_data

```{r}
total= merge(neighbor_data, outcome_two_data, by="ceb") %>% 
  mutate(bmi_cat = factor(bmi_cat, levels = c("normal", "overweight", "obese")),
         fbg_cat = factor(fbg_cat, levels = c("normal", "prediabetes", "diabetes")),
         hyp_cat = factor(hyp_cat, levels = c("normal", "hypertensive", "hypertension"))
         )

head(total)
```
