---
title: "Descriptive Stats"
Output: github_document
Author: Naina Ahuja
---

```{r setup, include=FALSE, message=FALSE, warnings=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
```
Loading and cleaning the data
```{r message=FALSE, warning=FALSE}
outcome_data = 
  read_excel("./Data/temp_data.xlsx", sheet = 3) %>%
  separate(sbp, into = c("sbp", "sbp_sd")) %>% 
  separate(dbp, into = c("dbp", "dbp_sd")) %>% 
  separate(  bmi, into = c("bmi", "bmi_sd")) %>% 
  janitor::clean_names() %>% 
  mutate(ceb = as.numeric(ceb),
         fbg = as.numeric(fbg),
         fbg_sd = as.numeric(fbg_sd),
         sbp = as.numeric(sbp),
         sbp_sd = as.numeric(sbp_sd),
         dbp = as.numeric(dbp),
         dbp_sd = as.numeric(dbp_sd),
         bmi = as.numeric(bmi),
         bmi_sd = as.numeric(bmi_sd),
         hypertension = as.numeric(hypertension),
         diabetes = as.numeric(diabetes)
         ) 
outcome_data
```

Looking at outcomes distribution- fasting blood glucose
```{r message=FALSE, warning=FALSE}
fbg_distribution = 
  ggplot(outcome_data, aes(x=fbg)) +
  geom_histogram(color = "black") 

fbg_distribution
```

Looking at outcomes distribution- sbp
```{r message= FALSE, warning=FALSE}
sbp_distribution = 
  ggplot(outcome_data, aes(x=sbp)) +
  geom_histogram(color = "black")

sbp_distribution
```

Looking at outcomes distribution- dbp
```{r message= FALSE, warning=FALSE}
dbp_distribution = 
  ggplot(outcome_data, aes(x= dbp)) +
  geom_histogram(color = "black")

dbp_distribution
```

Looking at outcomes distribution- bmi
```{r message = FALSE, warning=FALSE}
bmi_distribution = 
  ggplot(outcome_data, aes(x= bmi)) +
  geom_histogram(color = "black")

bmi_distribution
```