---
title: 'Model 2: BMI'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(data.table)
library(nnet)
```
Running the crude model
```{r}
crude_bmi = 
  multinom(bmi_cat ~ fuel_used_for_cooking_percent_wood_dung + percent_public_source + percent_private_toilet + percent_employed + percent_without_hs_education + percent_caste, data=total)

summary(crude_bmi)
```
Running the model with age as a confounder
```{r}
age_bmi = 
  multinom(bmi_cat ~ fuel_used_for_cooking_percent_wood_dung + percent_public_source + percent_private_toilet + percent_employed + percent_without_hs_education + percent_caste + median_age, data=total)

summary(age_bmi)
```
Running the model with sex as a confounder
```{r}
sex_bmi = 
  multinom(bmi_cat ~ fuel_used_for_cooking_percent_wood_dung + percent_public_source + percent_private_toilet + percent_employed + percent_without_hs_education + percent_caste + percent_female, data=total)

summary(sex_bmi)
```
Running the model with marital status as a confounder
```{r}
marital_bmi = 
  multinom(bmi_cat ~ fuel_used_for_cooking_percent_wood_dung + percent_public_source + percent_private_toilet + percent_employed + percent_without_hs_education + percent_caste + percent_marital_status, data=total)

summary(marital_bmi)
```



